backend:
    name: git-gateway
    branch: master

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
site_url: https://sinelanguage-ui.netlify.com
logo_url: https://sinelanguage-ui.netlify.com/images/logo.jpg

collections:
    - name: 'artist'
      extension: json
      label: 'Artist'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'artist' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'artist' }
          - { label: 'Unique Id (No spaces)', name: 'id', widget: 'string' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'artists/{{id}}' }
          - { label: 'Name', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
          - { label: 'Biography', name: 'body', widget: 'markdown' }
    - name: 'release'
      extension: json
      label: 'Release'
      folder: 'src/data'
      create: true
      identifier_field: code
      filter: { field: 'layout', value: 'release' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'release' }
          - { label: 'Code', name: 'code', hint: 'e.g. SLRXXX', widget: 'string' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'releases/{{code}}' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
    - name: 'podcast'
      extension: json
      label: 'Podcast'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'podcast' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'podcast' }
          - { label: 'Catalog Number', hint: 'e.g. SLRXXX', name: 'id', widget: 'string' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'podcasts/{{id}}' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'date' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
    - name: 'event'
      extension: json
      label: 'Event'
      folder: 'src/data'
      create: true
      filter: { field: 'layout', value: 'event' }
      slug: '{{layout}}_{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
          - { label: 'Url', name: 'url', widget: 'hidden', default: 'events/{{id}}' }
          - { label: 'Catalog Number', name: 'id', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'date', format: 'YYMMDD' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
