backend:
    name: git-gateway
    branch: master

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
site_url: https://sinelanguage-ui.netlify.com
logo_url: https://sinelanguage-ui.netlify.com/images/logo.jpg

collections:
    - name: 'artist'
      extension: json
      label: 'Artist'
      folder: 'src/data/artist'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'artist' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
          - { label: 'Biography', name: 'body', widget: 'markdown' }
    - name: 'podcast'
      extension: json
      label: 'Podcast'
      folder: 'src/data/podcast'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'podcast' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'thumbnail', widget: 'image' }
    - label: 'Blog in English'
      extension: json
      name: 'english_posts'
      folder: 'src/data/post'
      create: true
      filter: { field: 'language', value: 'en' }
      fields:
          - { label: 'Language', name: 'language', widget: 'select', options: ['en', 'es'] }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
          - { label: 'Tagline', name: 'tagline', widget: 'string' }
    - label: 'Blog en Español'
      extension: json
      name: 'spanish_posts'
      folder: 'src/data/post'
      create: true
      filter: { field: 'language', value: 'es' }
      fields:
          - { label: 'Lenguaje', name: 'language', widget: 'select', options: ['en', 'es'] }
          - { label: 'Titulo', name: 'title', widget: 'string' }
          - { label: 'Contenido', name: 'body', widget: 'markdown' }
          - { label: 'DifferentField', name: 'differentField', widget: 'string' }
